# Generated by Django 5.1.8 on 2025-04-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('success', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
