# Generated by Django 5.1.8 on 2025-04-12 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_data', '0003_syncconfiguration_syncresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncresult',
            name='configuration',
        ),
        migrations.DeleteModel(
            name='SyncConfiguration',
        ),
        migrations.DeleteModel(
            name='SyncResult',
        ),
    ]
