# Generated by Django 5.1.8 on 2025-04-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_data', '0006_fixturedata_query_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguedata',
            name='coverage_fixtures',
            field=models.BooleanField(default=False, verbose_name='Cobertura fixtures'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='coverage_fixtures_events',
            field=models.BooleanField(default=False, verbose_name='Cobertura eventos'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='coverage_fixtures_lineups',
            field=models.BooleanField(default=False, verbose_name='Cobertura alineaciones'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='coverage_fixtures_statistics_fixtures',
            field=models.BooleanField(default=False, verbose_name='Cobertura estadísticas partidos'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='coverage_fixtures_statistics_players',
            field=models.BooleanField(default=False, verbose_name='Cobertura estadísticas jugadores'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='coverage_injuries',
            field=models.BooleanField(default=False, verbose_name='Cobertura lesiones'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='coverage_odds',
            field=models.BooleanField(default=False, verbose_name='Cobertura apuestas'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='coverage_players',
            field=models.BooleanField(default=False, verbose_name='Cobertura jugadores'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='coverage_predictions',
            field=models.BooleanField(default=False, verbose_name='Cobertura predicciones'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='coverage_top_assists',
            field=models.BooleanField(default=False, verbose_name='Cobertura asistencias'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='coverage_top_cards',
            field=models.BooleanField(default=False, verbose_name='Cobertura tarjetas'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='coverage_top_scorers',
            field=models.BooleanField(default=False, verbose_name='Cobertura goleadores'),
        ),
    ]
