# Generated by Django 5.1.8 on 2025-04-24 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_data', '0008_livefixturetask_liveoddstask_livefixturedata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveOddsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(verbose_name='ID de categoría')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('odds_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_categories', to='sports_data.liveoddsdata', verbose_name='Datos de cuotas')),
            ],
            options={
                'verbose_name': 'Categoría de cuotas',
                'verbose_name_plural': 'Categorías de cuotas',
            },
        ),
        migrations.CreateModel(
            name='LiveOddsValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Valor')),
                ('odd', models.CharField(max_length=50, verbose_name='Cuota')),
                ('handicap', models.CharField(blank=True, max_length=50, null=True, verbose_name='Handicap')),
                ('main', models.BooleanField(blank=True, null=True, verbose_name='Principal')),
                ('suspended', models.BooleanField(default=False, verbose_name='Suspendido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='sports_data.liveoddscategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Valor de cuota',
                'verbose_name_plural': 'Valores de cuotas',
            },
        ),
        migrations.AddIndex(
            model_name='liveoddscategory',
            index=models.Index(fields=['category_id'], name='sports_data_categor_e011fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='liveoddscategory',
            unique_together={('odds_data', 'category_id')},
        ),
        migrations.AlterUniqueTogether(
            name='liveoddsvalue',
            unique_together={('category', 'value', 'handicap')},
        ),
    ]
