# Generated by Django 5.1.8 on 2025-04-25 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_data', '0009_liveoddscategory_liveoddsvalue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livefixturedata',
            options={'verbose_name': 'Partido en vivo', 'verbose_name_plural': 'live_Partidos en vivo'},
        ),
        migrations.AlterModelOptions(
            name='livefixturetask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tarea de partidos en vivo', 'verbose_name_plural': 'Live_Tareas de partidos en vivo'},
        ),
        migrations.AlterModelOptions(
            name='liveoddscategory',
            options={'verbose_name': 'Categoría de cuotas', 'verbose_name_plural': 'live_Categorías de cuotas'},
        ),
        migrations.AlterModelOptions(
            name='liveoddsdata',
            options={'verbose_name': 'Cuota en vivo', 'verbose_name_plural': 'live_Cuotas en vivo'},
        ),
        migrations.AlterModelOptions(
            name='liveoddstask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tarea de cuotas en vivo', 'verbose_name_plural': 'live_Tareas de cuotas en vivo'},
        ),
        migrations.AlterModelOptions(
            name='liveoddsvalue',
            options={'verbose_name': 'Valor de cuota', 'verbose_name_plural': 'live_Valores de cuotas'},
        ),
        migrations.AlterField(
            model_name='liveoddscategory',
            name='odds_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_categories', to='sports_data.liveoddsdata', verbose_name='live_Datos de cuotas'),
        ),
    ]
