# Generated by Django 5.1.8 on 2025-04-14 02:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppUser',
            fields=[
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Número de teléfono')),
                ('profile_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de perfil')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='En lista negra')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('registered', 'Registrado'), ('suspended', 'Suspendido'), ('banned', 'Bloqueado')], default='new', max_length=20, verbose_name='Estado')),
                ('subscription_plan', models.CharField(choices=[('free', 'Gratuito'), ('premium', 'Premium'), ('pro', 'Profesional')], default='free', max_length=20, verbose_name='Plan de suscripción')),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Expiración de suscripción')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última actividad')),
            ],
            options={
                'verbose_name': 'Usuario de WhatsApp',
                'verbose_name_plural': 'Usuarios de WhatsApp',
                'indexes': [models.Index(fields=['status'], name='whatsapp_wh_status_c0e040_idx'), models.Index(fields=['subscription_plan'], name='whatsapp_wh_subscri_a9e777_idx'), models.Index(fields=['is_blacklisted'], name='whatsapp_wh_is_blac_0e27d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_teams', models.JSONField(blank=True, default=list, verbose_name='Equipos favoritos')),
                ('favorite_leagues', models.JSONField(blank=True, default=list, verbose_name='Ligas favoritas')),
                ('notification_preferences', models.JSONField(blank=True, default=dict, verbose_name='Preferencias de notificación')),
                ('language', models.CharField(default='es', max_length=10, verbose_name='Idioma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='whatsapp.whatsappuser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de usuario',
                'verbose_name_plural': 'Preferencias de usuarios',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=100, verbose_name='ID del hilo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('last_message_at', models.DateTimeField(auto_now_add=True, verbose_name='Último mensaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='whatsapp.whatsappuser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del mensaje')),
                ('is_from_user', models.BooleanField(default=True, verbose_name='Es del usuario')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('message_type', models.CharField(default='text', max_length=20, verbose_name='Tipo de mensaje')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.conversation', verbose_name='Conversación')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation'], name='whatsapp_me_convers_595289_idx'), models.Index(fields=['is_from_user'], name='whatsapp_me_is_from_557755_idx'), models.Index(fields=['created_at'], name='whatsapp_me_created_f75820_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.CharField(max_length=100, verbose_name='ID del flujo')),
                ('flow_token', models.CharField(max_length=255, verbose_name='Token del flujo')),
                ('screen_id', models.CharField(max_length=100, verbose_name='ID de pantalla')),
                ('data', models.JSONField(verbose_name='Datos del formulario')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='whatsapp.whatsappuser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Input de usuario',
                'verbose_name_plural': 'Inputs de usuario',
                'indexes': [models.Index(fields=['user'], name='whatsapp_us_user_id_c971d4_idx'), models.Index(fields=['flow_id'], name='whatsapp_us_flow_id_ebc5dc_idx'), models.Index(fields=['created_at'], name='whatsapp_us_created_456941_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['thread_id'], name='whatsapp_co_thread__383f46_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_active'], name='whatsapp_co_is_acti_751d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'is_active'], name='whatsapp_co_user_id_763eed_idx'),
        ),
    ]
