# Generated by Django 5.1.8 on 2025-04-14 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_conversationsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen de la conversación'),
        ),
        migrations.AlterField(
            model_name='conversationsummary',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_summary', to='whatsapp.conversation', verbose_name='Conversación'),
        ),
    ]
