# Generated by Django 5.1.8 on 2025-04-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_remove_conversation_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='preserve_context',
            field=models.BooleanField(default=False, help_text='Si es True, el contexto de la conversación se preservará para usuarios premium', verbose_name='Preservar contexto'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['preserve_context'], name='whatsapp_co_preserv_caa9bc_idx'),
        ),
    ]
