# Generated by Django 5.1.8 on 2025-04-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_conversation_preserve_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='request_json',
            field=models.JSONField(blank=True, help_text='JSON completo recibido del webhook o enviado a la API', null=True, verbose_name='JSON de solicitud'),
        ),
        migrations.AddField(
            model_name='message',
            name='response_json',
            field=models.JSONField(blank=True, help_text='JSON completo de respuesta de la API o enviado al cliente', null=True, verbose_name='JSON de respuesta'),
        ),
    ]
