# Generated by Django 5.1.8 on 2025-04-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_message_request_json_message_response_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('SYSTEM', 'Sistema'), ('GENERAL', 'General'), ('PREDICTIONS', 'Predicciones'), ('LIVE_ODDS', 'Cuotas en vivo'), ('BETTING', 'Apuestas')], default='GENERAL', max_length=20, verbose_name='Tipo de conversación'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='fixture_id',
            field=models.CharField(blank=True, help_text='ID del partido al que se refiere la conversación, si aplica', max_length=100, null=True, verbose_name='ID del partido'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type'], name='whatsapp_co_convers_40a6f5_idx'),
        ),
    ]
