# Generated by Django 5.1.8 on 2025-05-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_assistantconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantconfig',
            name='experience_level',
            field=models.CharField(default='media', max_length=50, verbose_name='Nivel de experiencia'),
        ),
        migrations.AlterField(
            model_name='assistantconfig',
            name='language_style',
            field=models.CharField(default='normal', max_length=50, verbose_name='Estilo de lenguaje'),
        ),
    ]
